### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Varbaek** [akibsayyed/safeseven#4]
```
Pattern in byte  12
1274 [main] DEBUG org.matrixshell.mapScanner.SS7_server  - Initializing TCAP Stack ....
1389 [main] WARN  org.mobicents.protocols.ss7.tcap.TCAPStackImpl-TCAP  - Failed to load the TCAP Management configuration file. 
/root/Desktop/SS7/safe7/safeseven/TCAP_management.xml (No such file or directory)
1486 [main] DEBUG org.matrixshell.mapScanner.SS7_server  - Initializing MAP Stack ....
1646 [main] DEBUG org.matrixshell.mapScanner.SS7_server  - Initialized MAP Stack ....
1647 [main] DEBUG org.matrixshell.mapScanner.SS7_server  - Starting ASP
1648 [main] DEBUG org.matrixshell.mapScanner.SS7_server  - ASP Started
1649 [main] DEBUG org.matrixshell.mapScanner.SS7_server  - Stack Initilized
11796 [Thread-0] ERROR org.mobicents.protocols.sctp.SelectorThread  - Exception while finishing connection for Association=clientAsscoiation
java.net.ConnectException: Connection refused
	at sun.nio.ch.SctpChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SctpChannelImpl.finishConnect(SctpChannelImpl.java:475)
	at org.mobicents.protocols.sctp.SelectorThread.finishConnectionSctp(SelectorThread.java:381)
	at org.mobicents.protocols.sctp.SelectorThread.finishConnection(SelectorThread.java:366)
	at org.mobicents.protocols.sctp.SelectorThread.run(SelectorThread.java:151)
	at java.lang.Thread.run(Thread.java:745)
21823 [Thread-0] ERROR org.mobicents.protocols.sctp.SelectorThread  - Exception while finishing connection for Association=clientAsscoiation
java.net.ConnectException: Connection refused
	at sun.nio.ch.SctpChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SctpChannelImpl.finishConnect(SctpChannelImpl.java:475)
	at org.mobicents.protocols.sctp.SelectorThread.finishConnectionSctp(SelectorThread.java:381)
	at org.mobicents.protocols.sctp.SelectorThread.finishConnection(SelectorThread.java:366)
	at org.mobicents.protocols.sctp.SelectorThread.run(SelectorThread.java:151)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by Varbaek** [comment]
`safeseven/TCAP_management.xml (No such file or directory)`

**Comment by gpsangamesh007** [comment]
I am facing following exception while running STP.jar
11796 [Thread-0] ERROR org.mobicents.protocols.sctp.SelectorThread  - Exception while finishing connection for Association=clientAsscoiation
java.net.ConnectException: Connection refused

Please suggest the solution for the same

**Comment by mmali277** [comment]
@Varbaek  is your prblem solved?? if yes, please help me too...

**Comment by ilketoprak17** [comment]
same error... help pls?

**Comment by hemanthrebel** [comment]
Can anyone please tell me how to find the Ip of STP I'm connecting to and others mentioned in client_config file to be edited.

**Comment by yychaza1412** [comment]
hi can you help me to set my client_config please

**Comment by yychaza1412** [comment]
contact me on alexijo1412@protonmail.com
